@extends('layouts.app')
@section('headername',  'Referral' )
@section('bread1',  'My Account' )
@section('bread2',  'Referral' )


@section('header')

@endsection




@section('footer')
<script src="{{ asset('assets/js/custom/account/referrals/referral-program.js') }}"></script>
@endsection






@section('slot')
<!--begin::Content-->
<div class="content d-flex flex-column flex-column-fluid" id="kt_content">
    <!--begin::Container-->
    <div class="container-xxl" id="kt_content_container">
        <!--begin::Row-->
        @include('admin.components.alert')

        <!--begin::Referral program-->
        <div class="card mb-5 mb-xl-10">
            <!--begin::Body-->
            <div class="card-body py-10">
                <h2 class="mb-9">Referral Program</h2>
                <!--begin::Overview-->
                <div class="row mb-10">
                    <!--begin::Col-->
                    <div class="col-xl-6 mb-15 mb-xl-0 pe-5">
                        <h4 class="mb-0">How it works!</h4>
                        <p class="fs-6 fw-semibold text-gray-600 py-4 m-0">The DealsIntel Affiliate Referral Program is a unique opportunity for affiliate marketers to enhance their earnings by referring other affiliate marketers to the DealsIntel platform. By participating in this program, you can earn 5% of the earnings generated by the affiliates you refer for a period of 6 months.
                        </p>
                        <p class="fs-6 fw-semibold text-gray-600 py-4 m-0">Your earnings are calculated automatically and credited to your DealsIntel account.</p>
                    </div>
                    <!--end::Col-->
                    <!--begin::Col-->
                    <div class="col-xl-6">
                        <h4 class="text-gray-800 mb-0">Your Referral Link</h4>
                        <p class="fs-6 fw-semibold text-gray-600 py-4 m-0">Share your referral link with potential affiliate marketers via social media, email, blogs, forums, or any other platform where you engage with other marketers
                        </p>
                        <p class="fs-6 fw-semibold text-gray-600 py-4 m-0">Remember to highlight the benefits of joining the DealsIntel Affiliate Program to attract more affiliates</p>
                        <div class="d-flex">
                            <input id="kt_referral_link_input" type="text" class="form-control form-control-solid me-3 flex-grow-1" name="search" value="{{ $refURL }}" />
                            <button id="kt_referral_program_link_copy_btn" class="btn btn-light btn-active-light-primary fw-bold flex-shrink-0" data-clipboard-target="#kt_referral_link_input">Copy Link</button>
                        </div>
                    </div>
                    <!--end::Col-->
                </div>
                <!--end::Overview-->
                
                <!--end::Stats-->
                <!--begin::Info-->
                <p class="fs-5 fw-semibold text-gray-600 py-6">Leveraging the power of the DealsIntel Affiliate Referral Program, you can significantly enhance your affiliate marketing income with minimal additional effort. Happy referring!</p>
                <!--end::Info-->
                
            </div>
            <!--end::Body-->
        </div>
        <!--end::Referral program-->
        
    </div>
</div>
@endsection